config/routes.rb
Rails.application.routes.draw do

  # JSON POST Request route
  post "/api/v1/products", to: "api/v1/products#create"

  # Backoffice Admin routes
  scope :admin do
    resources :products, only: [:index, :edit, :update]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  # Validations
  validates :name, presence: true

  # Associations
  has_and_belongs_to_many :products

  def self.find_by_another_category
    puts "this is testing"
  end
end

app/models/image.rb
class Image < ActiveRecord::Base

  # Attachment
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }

  # Validations
  validates_attachment_content_type :img,
                                    :content_type => ['image/png', 'image/jpg', 'image/jpeg', 'image/gif'],
                                    :message => "must be .png, .jpg or .jpeg or .gif files"

  # Associations
  belongs_to :product
end

app/models/model.rb
class Model < ActiveRecord::Base

  # Validations
  validates :name, presence: true

  # Associations
  has_and_belongs_to_many :vars
end

app/models/product.rb
class Product < ActiveRecord::Base

  # Validations
  validates :name, presence: true, uniqueness: true

  # Associations
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :categories
  has_one :var, dependent: :destroy
  has_many :images, dependent: :destroy
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  # Validations
  validates :name, presence: true

  # Associations
  has_and_belongs_to_many :products
end

app/models/var.rb
class Var < ActiveRecord::Base
  enum color: [:black, :red, :blue, :white, :green]

  # Associations
  belongs_to :product
  has_and_belongs_to_many :models
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:create]

  def create
    parser = ParameterParser.new(params)
    parser.parse
    product_creator_service = ProductCreatorService.new(parser.product_params, parser.var_params)
    if product_creator_service.create_product
      render json: { message: "Product created successfully." }, status: 200
    else
      render json: { message: product_creator_service.errors }, status: 422
    end
  end

  private

  def product_params
    params.permit(:name, :description, :expire_date, :price, :collection_id, :SKU_ID, category_ids: [], tag_ids: [])
  end

  def var_params
    params.require(:vars).permit(:color) if params[:vars].present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :update_categories_tags, only: [:update]
  before_action :populate_data, only: [:edit, :update]

  def index
    @products = Product.includes(:categories, :tags, :images, var: :models).all
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.var = Var.new(var_params)
    if @product.update_attributes(product_params)
      flash[:success] = "Product updated successfully."
      redirect_to products_path
    else
      flash.now[:danger] = @product.errors.full_messages.join("\n")
      render "edit"
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :collection_id, :SKU_ID, :price, :expire_date, category_ids: [], tag_ids: [])
  end

  def var_params
    params[:product].require(:var).permit(:color, model_ids: [])
  end

  def update_categories_tags
    params[:product][:category_ids] ||= []
    params[:product][:tag_ids] ||= []
    params[:product][:var][:model_ids] ||= []
  end

  def populate_data
    @tags = Tag.all
    @categories = Category.all
    @colors = Var.colors
    @models = Model.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestfulProducts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_categories.html.erb
<table>
  <% categories.each do |category| %>
    <tr>
      <td><%= check_box_tag "product[category_ids][]", category.id, product.categories.include?(category) %></td>
      <td><%= category.name %></td>
    </tr>
  <% end %>
</table>

app/views/products/_colors.html.erb
<table>
  <% colors.each do |color| %>
    <tr>
      <td><%= radio_button_tag "product[var][color]", color[0], product.var.present? ? product.var.color == color[0] : "" %></td>
      <td><%= color[0].titleize %></td>
    </tr>
  <% end %>
</table>

app/views/products/_form.html.erb
<%= form_for product do |f| %>
  <table width="100%">
    <tr>
      <td width="33%">
        <table>
          <tr>
            <td>Name:</td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td>Description:</td>
            <td><%= f.text_field :description %></td>
          </tr>
          <tr>
            <td>Expire Date:</td>
            <td><%= f.text_field :expire_date %>(yyyy-mm-dd)</td>
          </tr>
          <tr>
            <td>Price:</td>
            <td><%= f.text_field :price %></td>
          </tr>
          <tr>
            <td>Collection ID:</td>
            <td><%= f.text_field :collection_id %></td>
          </tr>
          <tr>
            <td>SKU ID:</td>
            <td><%= f.text_field :SKU_ID %></td>
          </tr>
        </table>
      </td>
      <td width="33%">
        <h2>Categories</h2>
        <%= render partial: "categories", locals: { product: @product, categories: @categories } %>
      </td>
      <td width="33%">
        <h2>Tags</h2>
        <%= render partial: "tags", locals: { product: @product, tags: @tags } %>
      </td>
    </tr>
    <h2>Vars</h2>
    <tr>
      <td>
        <h2>Colors</h2>
        <%= render partial: "colors", locals: { product: @product, colors: @colors } %>
      </td>
      <td>
        <h2>Models</h2>
        <%= render partial: "models", locals: { product: @product, models: @models } %>
      </td>
      <td>
        <h2>Images</h2>
        <%= render partial: "images", locals: { product: @product } %>
      </td>
    </tr>
  </table>
  <%= f.submit %>
<% end %>

app/views/products/_images.html.erb
<table>
   <% product.images.each do |image| %>
    <tr>
      <td><%= image_tag image.img.url(:thumb) %></td>
    </tr>
  <% end %>
</table>

app/views/products/_models.html.erb
<table>
  <% models.each do |model| %>
    <tr>
      <td><%= check_box_tag "product[var][model_ids][]", model.id, product.var.present? && product.var.models.include?(model) %></td>
      <td><%= model.name %></td>
    </tr>
  <% end %>
</table>

app/views/products/_tags.html.erb
<table>
  <% tags.each do |tag| %>
    <tr>
      <td><%= check_box_tag "product[tag_ids][]", tag.id, product.tags.include?(tag) %></td>
      <td><%= tag.name %></td>
    </tr>
  <% end %>
</table>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>
<%= render partial: "shared/errors", locals: {object: @product} %>
<%= render partial: "form", locals: {product: @product} %>

app/views/products/index.html.erb
<h1>Products</h1>
<%= render partial: "shared/errors" %>
<table border=1 width="100%">
  <tr>
    <th>Name</th>
    <th>SKU_ID</th>
    <th>Price</th>
    <th>Picture</th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td width="25%" align="center"><%= link_to product.name, edit_product_url(product) %></td>
      <td width="25%" align="center"><%= product.SKU_ID %></td>
      <td width="25%" align="center"><%= product.price %></td>
      <td width="25%" align="center"><%= image_tag product.images.first.img.url(:thumb) unless product.images.empty? %></td>
    </tr>
  <% end %>
</table>

app/views/shared/_errors.html.erb
<div class="flash-messages">
  <% if flash.any? %>
    <% flash.each do |message_type, message| %>
      <% if message.is_a? Array %>
        <% message.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      <% else %>
        <%= message.html_safe %>
      <% end %>
    <% end %>
  <% end %>
</div>